language: objective-c

branches:
  only:
    - master

osx_image: xcode8

script:
  - xcodebuild -workspace RichString.xcworkspace -scheme "RichString iOS" -destination "platform=iOS Simulator,name=Generic iOS Simulator Device" test
